# Generated by Django 4.2.7 on 2023-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='categories',
            field=models.ManyToManyField(default=None, null=True, to='kab_rus_dictionary.category'),
        ),
    ]
