# Generated by Django 4.2.7 on 2023-12-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0004_alter_translation_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='same',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sames', to='kab_rus_dictionary.translation'),
        ),
    ]
