# Generated by Django 4.2.7 on 2023-12-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0008_alter_translation_same'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='same',
        ),
        migrations.AddField(
            model_name='translation',
            name='same_words',
            field=models.ManyToManyField(to='kab_rus_dictionary.translation'),
        ),
    ]
