# Generated by Django 4.2.7 on 2023-12-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0009_remove_translation_same_translation_same_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='same_words',
            field=models.ManyToManyField(blank=True, to='kab_rus_dictionary.translation'),
        ),
    ]
