# Generated by Django 4.2.7 on 2023-12-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0011_remove_translation_same_words_samewords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SameWords',
        ),
    ]
