# Generated by Django 4.2.7 on 2023-12-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0012_delete_samewords'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='translation_kab',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
