# Generated by Django 4.2.7 on 2023-12-30 12:34

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0013_category_description_category_translation_kab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ages', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('description_kab', models.TextField()),
                ('description_rus', models.TextField()),
            ],
        ),
    ]
