# Generated by Django 4.2.7 on 2024-03-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0014_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabword',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True),
        ),
    ]
