# Generated by Django 4.2.7 on 2024-03-31 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0015_alter_kabword_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabword',
            name='synonym',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='synonyms', to='kab_rus_dictionary.kabword'),
        ),
    ]
