# Generated by Django 4.2.7 on 2024-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0016_kabword_synonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabword',
            name='synonym',
        ),
        migrations.AddField(
            model_name='kabword',
            name='synonyms',
            field=models.ManyToManyField(blank=True, to='kab_rus_dictionary.kabword'),
        ),
    ]
