# Generated by Django 4.2.7 on 2024-06-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0019_language_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('translation', models.TextField()),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kab_rus_dictionary.kabword')),
            ],
        ),
    ]
