# Generated by Django 4.2.7 on 2024-06-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0020_proverb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleOfUseKabWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField()),
                ('translation', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kab_rus_dictionary.kabword')),
            ],
        ),
    ]
