# Generated by Django 4.2.7 on 2024-07-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0021_exampleofusekabword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleofusekabword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='kab_rus_dictionary.kabword'),
        ),
        migrations.CreateModel(
            name='KabWordRelatedPhrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='kab_rus_dictionary.kabword')),
            ],
        ),
    ]
