# Generated by Django 4.2.7 on 2024-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kab_rus_dictionary', '0022_alter_exampleofusekabword_word_kabwordrelatedphrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabwordrelatedphrases',
            name='translation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exampleofusekabword',
            name='example',
            field=models.CharField(max_length=255),
        ),
    ]
