# Generated by Django 4.2.7 on 2023-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KabNaturalNumber',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('translate_decimal', models.CharField(max_length=128)),
                ('translate_twentieth', models.CharField(default=None, max_length=128, null=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
