# Generated by Django 4.2.7 on 2024-04-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kab_numerals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabnaturalnumber',
            name='translate_twentieth',
        ),
    ]
