# Generated by Django 4.2.7 on 2023-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KabLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(db_index=True, max_length=4, unique=True)),
                ('slug', models.SlugField(max_length=4, unique=True)),
                ('is_vowel', models.BooleanField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
