# Generated by Django 4.2.7 on 2024-03-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kab_alphabet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabletter',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=4, unique=True),
        ),
    ]
